# Generated by Django 4.2.16 on 2024-11-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
