# Generated by Django 4.2.16 on 2024-11-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='style',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
