# Generated by Django 4.2.16 on 2024-11-20 12:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_deposit_fin_prdt_cd_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="deposit_fin_prdt_cd",
        ),
        migrations.RemoveField(
            model_name="user",
            name="saving_fin_prdt_cd",
        ),
    ]
